
supabaseUrl =https://nqadaafwcsfmodriviqm.supabase.co
supabaseKey =sb_publishable_XqqVuG9cocpmzhU6xVJJ3A__jTklElY

supabaseUrlProd =https://nqadaafwcsfmodriviqm.supabase.co
supabaseKeyProd =sb_publishable_XqqVuG9cocpmzhU6xVJJ3A__jTklElY